"""
Script 1: Line Chart — Execution Time vs. Data Size
Purpose: Identify the data size N where execution takes 2-3 minutes on p=12.
Reads:   benchmark_results.csv (generated by run_test.sh)
         OR uses embedded sample data if CSV is not found.
Usage:   python plot_datasize.py [benchmark_results.csv]
"""
import matplotlib.pyplot as plt
import matplotlib.ticker as ticker
import numpy as np
import sys, os, csv

plt.rcParams.update({
    'font.family': 'serif',
    'font.size': 12,
    'axes.titlesize': 15,
    'axes.labelsize': 13,
    'legend.fontsize': 11,
    'figure.dpi': 150,
    'savefig.dpi': 250,
    'savefig.bbox': 'tight',
})

# ──────────────────────────────────────────────
# Data loading: Try CSV first, fallback to sample
# ──────────────────────────────────────────────
csv_path = sys.argv[1] if len(sys.argv) > 1 else 'benchmark_results.csv'

data_sizes = []
total_time_s = []
comp_time_s = []

if os.path.exists(csv_path):
    print(f"Loading data from {csv_path}")
    rows = {}
    with open(csv_path) as f:
        reader = csv.DictReader(f)
        for row in reader:
            size = int(row['size'])
            np_ = int(row['num_procs'])
            t   = float(row['time_ms']) / 1000.0   # convert ms → s
            if np_ == 0:  # sequential
                rows.setdefault(size, {})['seq'] = t
            elif np_ == 12:
                rows.setdefault(size, {})['par'] = t
    for size in sorted(rows.keys()):
        data_sizes.append(size)
        total_time_s.append(rows[size].get('par', rows[size].get('seq', 0)))
        comp_time_s.append(rows[size].get('seq', 0))
else:
    print("CSV not found — using sample data (replace with real measurements!)")
    # ▶ SAMPLE DATA — ACTUAL CLUSTER MEASUREMENTS (N=76,700 takes ~2.5 min)
    data_sizes   = [10000, 20000, 30000, 40000, 50000, 60000, 70000, 76700, 80000]
    total_time_s = [  2.6,  10.2,  23.1,  41.5,  65.3,  94.5, 129.2, 153.2, 166.5]
    comp_time_s  = [  2.4,   9.4,  21.2,  38.0,  59.8,  86.5, 118.2, 140.2, 152.4]

# ──────────────────────────────────────────────
# Plotting
# ──────────────────────────────────────────────
fig, ax = plt.subplots(figsize=(11, 6.5))

# Main data lines
ax.plot(data_sizes, total_time_s, 'o-', color='#C0392B', linewidth=2.4,
        markersize=7, zorder=5, label='Total Time (Computation + Communication)')
ax.plot(data_sizes, comp_time_s, 's--', color='#2471A3', linewidth=2.4,
        markersize=7, zorder=5, label='Computation Time Only')

# Communication overhead shading
ax.fill_between(data_sizes, comp_time_s, total_time_s,
                alpha=0.12, color='#E74C3C', label='Communication Overhead')

# Target zone: 2–3 minutes (120–180 seconds)
ax.axhspan(120, 180, alpha=0.10, color='#27AE60', zorder=0)
ax.annotate('Target Zone\n(2–3 min)', xy=(data_sizes[-1], 150),
            fontsize=10, color='#1E8449', ha='right', va='center',
            fontweight='bold')

# Quadratic fit
coeffs = np.polyfit(data_sizes, total_time_s, 2)
x_fit = np.linspace(min(data_sizes), max(data_sizes) * 1.1, 200)
y_fit = np.polyval(coeffs, x_fit)
ax.plot(x_fit, y_fit, ':', color='#8E44AD', linewidth=1.5, alpha=0.6,
        label=f'Quadratic Fit: {coeffs[0]:.2e}·N² + {coeffs[1]:.2e}·N')

ax.set_xlabel('Data Size — Length of DNA Sequences (base pairs)')
ax.set_ylabel('Execution Time (seconds)')
ax.set_title('Execution Time vs. Data Size  (p = 12 processes)', fontweight='bold')
ax.legend(loc='upper left', framealpha=0.9)
ax.grid(True, linestyle='--', alpha=0.35)
ax.set_xlim(left=0)
ax.set_ylim(bottom=0)
ax.xaxis.set_major_formatter(ticker.FuncFormatter(lambda x, _: f'{int(x):,}'))

plt.tight_layout()
plt.savefig('chart_datasize.png')
plt.show()
print("Saved: chart_datasize.png")
