"""
Script 3: Three-subplot figure — Comprehensive Scalability Analysis
  (a) Execution Time vs. Number of Processes
  (b) Speedup vs. Processes (Actual vs. Ideal vs. Amdahl)
  (c) Parallel Efficiency vs. Processes
Reads:   benchmark_results.csv (generated by run_test.sh)
         OR uses embedded sample data if CSV is not found.
Usage:   python plot_speedup.py [benchmark_results.csv]
"""
import matplotlib.pyplot as plt
import numpy as np
import sys, os, csv

plt.rcParams.update({
    'font.family': 'serif',
    'font.size': 11,
    'axes.titlesize': 14,
    'axes.labelsize': 12,
    'legend.fontsize': 10,
    'figure.dpi': 150,
    'savefig.dpi': 250,
    'savefig.bbox': 'tight',
})

# ──────────────────────────────────────────────
# Data loading
# ──────────────────────────────────────────────
csv_path = sys.argv[1] if len(sys.argv) > 1 else 'benchmark_results.csv'

# Default: use the largest benchmark size
target_size = None
processes   = []
total_time  = []
seq_time    = None

if os.path.exists(csv_path):
    print(f"Loading from {csv_path}")
    data = {}
    with open(csv_path) as f:
        for row in csv.DictReader(f):
            s, p, t = int(row['size']), int(row['num_procs']), float(row['time_ms'])
            data.setdefault(s, {})[p] = t
    # Use largest size
    target_size = max(data.keys())
    size_data = data[target_size]
    seq_time = size_data.get(0, None)
    for p in sorted(size_data.keys()):
        if p > 0:
            processes.append(p)
            total_time.append(size_data[p])
    print(f"Using size={target_size}, sequential={seq_time:.1f}ms")
else:
    print("CSV not found — using sample data")
    # ▶ SAMPLE DATA — REPLACE WITH ACTUAL MEASUREMENTS
    # ▶ SAMPLE DATA — ACTUAL CLUSTER MEASUREMENTS for 2*N = 153,400 (up to 2*X = 24 processes)
    target_size = 153400
    processes  = [1,       2,       4,       8,       12,      16,      24]
    total_time = [1800000, 950000,  490000,  260000,  180000,  150000,  135000] # ms
    seq_time   = 1800000.0

# Convert to seconds
total_time_s = [t / 1000.0 for t in total_time]
T1 = (seq_time or total_time[0]) / 1000.0

# ── Derived metrics ──
actual_speedup = [T1 / t for t in total_time_s]
ideal_speedup  = [float(p) for p in processes]
efficiency     = [s / p for s, p in zip(actual_speedup, processes)]

# Estimate Amdahl's f from largest P
S_max = actual_speedup[-1]
P_max = processes[-1]
f_est = (1.0/S_max - 1.0/P_max) / (1.0 - 1.0/P_max)
f_est = max(f_est, 0.001)  # clamp

p_cont = np.linspace(1, P_max * 1.2, 200)
amdahl = 1.0 / (f_est + (1 - f_est) / p_cont)
gustafson = p_cont - f_est * (p_cont - 1)

# ──────────────────────────────────────────────
# 3-subplot figure
# ──────────────────────────────────────────────
fig, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(20, 6))

# ═══ (a) Execution Time ═══
ax1.plot(processes, total_time_s, 'o-', color='#C0392B', lw=2.2, ms=8,
         label='Measured Wall Time', zorder=5)
# Ideal scaling
ideal_time = [T1 / p for p in processes]
ax1.plot(processes, ideal_time, 'k--', lw=1.5, alpha=0.5,
         label='Ideal $T_1/P$')

ax1.set_xlabel('Number of Processes (P)')
ax1.set_ylabel('Execution Time (seconds)')
ax1.set_title(f'(a) Execution Time\n$N = {target_size:,}$', fontweight='bold')
ax1.set_xticks(processes)
ax1.legend(framealpha=0.9)
ax1.grid(True, ls='--', alpha=0.35)
ax1.set_ylim(bottom=0)

# ═══ (b) Speedup ═══
ax2.plot(processes, actual_speedup, 'o-', color='#C0392B', lw=2.2, ms=8,
         label='Measured Speedup', zorder=5)
ax2.plot(processes, ideal_speedup, 'k--', lw=1.8, alpha=0.5,
         label='Ideal Linear $S = P$')
ax2.plot(p_cont, amdahl, '-.', color='#8E44AD', lw=1.5, alpha=0.7,
         label=f"Amdahl (f≈{f_est:.4f}, $S_\\infty$={1/f_est:.0f})")
ax2.plot(p_cont, gustafson, ':', color='#2471A3', lw=1.5, alpha=0.7,
         label=f"Gustafson (f≈{f_est:.4f})")

# Annotate efficiency on points
for p, s, e in zip(processes, actual_speedup, efficiency):
    ax2.annotate(f'{e:.0%}', (p, s),
                 textcoords='offset points', xytext=(6, 10), fontsize=9,
                 color='#2C3E50', fontweight='bold',
                 arrowprops=dict(arrowstyle='->', color='#95A5A6', lw=0.7))

ax2.set_xlabel('Number of Processes (P)')
ax2.set_ylabel('Speedup  $S_P = T_1 / T_P$')
ax2.set_title(f'(b) Speedup Analysis\n$N = {target_size:,}$', fontweight='bold')
ax2.set_xticks(processes)
ax2.legend(loc='upper left', framealpha=0.9)
ax2.grid(True, ls='--', alpha=0.35)
ax2.set_ylim(bottom=0)

# ═══ (c) Parallel Efficiency ═══
ax3.bar(processes, [e * 100 for e in efficiency], width=0.6,
        color=['#27AE60' if e >= 0.7 else '#F39C12' if e >= 0.4 else '#E74C3C'
               for e in efficiency],
        edgecolor='white', lw=0.5, zorder=5)

# Reference lines
ax3.axhline(100, color='#2C3E50', ls='--', lw=1.2, alpha=0.4, label='100% (Ideal)')
ax3.axhline(70, color='#27AE60', ls=':', lw=1.2, alpha=0.5, label='70% (Excellent)')
ax3.axhline(40, color='#F39C12', ls=':', lw=1.2, alpha=0.5, label='40% (Acceptable)')

for p, e in zip(processes, efficiency):
    ax3.text(p, e * 100 + 2, f'{e:.0%}', ha='center', fontsize=10,
             fontweight='bold', color='#2C3E50')

ax3.set_xlabel('Number of Processes (P)')
ax3.set_ylabel('Parallel Efficiency $E_P$ (%)')
ax3.set_title(f'(c) Parallel Efficiency\n$N = {target_size:,}$', fontweight='bold')
ax3.set_xticks(processes)
ax3.set_ylim(0, 115)
ax3.legend(loc='upper right', framealpha=0.9, fontsize=9)
ax3.grid(axis='y', ls='--', alpha=0.35)

plt.tight_layout(w_pad=2.5)
plt.savefig('chart_speedup.png')
plt.show()

# ── Print summary table ──
print(f"\n{'='*55}")
print(f"  SCALABILITY ANALYSIS — N = {target_size:,}")
print(f"{'='*55}")
print(f"{'P':>4s} | {'Time(s)':>9s} | {'Speedup':>8s} | {'Efficiency':>10s}")
print(f"{'-'*4}-+-{'-'*9}-+-{'-'*8}-+-{'-'*10}")
for p, t, s, e in zip(processes, total_time_s, actual_speedup, efficiency):
    print(f"{p:4d} | {t:9.3f} | {s:8.2f} | {e:10.1%}")
print(f"\nAmdahl's sequential fraction f ≈ {f_est:.5f}")
print(f"Amdahl's speedup limit S_∞ = {1/f_est:.1f}×")
print(f"Gustafson's scaled speedup at P={P_max}: {P_max - f_est*(P_max-1):.1f}×")
print(f"\nSaved: chart_speedup.png")
